apiVersion: v1
kind: ConfigMap
metadata:
  name: consul
  namespace: vault
data:
  server.json: |
    {
      "ca_file": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
      "cert_file": "/etc/tls/cert.pem",
      "key_file": "/etc/tls/key.pem",
      "acl_datacenter": "us-east1",
      "acl_default_policy": "deny",
      "acl_enable_key_list_policy": true,
      "verify_incoming": false,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ports": {
        "https": 8443
      },
      "autopilot": {
        "cleanup_dead_servers": true,
        "last_contact_threshold": "300ms",
        "max_trailing_logs": 250,
        "server_stabilization_time": "10s"
      }
    }
