apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: consul
  namespace: vault
spec:
  serviceName: consul-internal
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul-internal
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - consul-internal
              topologyKey: failure-domain.beta.kubernetes.io/zone
      serviceAccountName: consul
      initContainers:
        - name: certificate-requestor
          image: gcr.io/the-psf/certificate-requestor:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "--additional-dnsnames=server.us-east1.cluster.local"
            - "--cert-dir=/etc/tls"
            - "--namespace=$(NAMESPACE)"
            - "--pod-ip=$(POD_IP)"
            - "--pod-name=$(POD_NAME)"
            - "--service-names=consul,consul-internal"
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
        - name: consul-secret-writer
          image: alpine:3.7
          env:
            - name: CONSUL_ACL_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-agent-token
                  key: token
            - name: GOSSIP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: consul-gossip-key
                  key: key
          command: ['/bin/sh']
          args: ['/opt/scripts/write-secrets.sh']
          volumeMounts:
            - name: consul-secrets
              mountPath: /etc/consul/secrets
            - name: consul-scripts
              mountPath: /opt/scripts
      containers:
        - name: consul
          image: consul:1.0.1
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INITIAL_CLUSTER_SIZE
              value: "3"  # This should not change once consul has been created.
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=$(INITIAL_CLUSTER_SIZE)"
            - "-retry-join=consul-0.consul-internal.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-1.consul-internal.$(NAMESPACE).svc.cluster.local"
            - "-retry-join=consul-2.consul-internal.$(NAMESPACE).svc.cluster.local"
            - "-client=0.0.0.0"
            - "-domain=cluster.local"
            - "-datacenter=us-east1"
            - "-config-file=/etc/consul/config/server.json"
            - "-config-dir=/etc/consul/secrets/"
            - "-server"
            - "-ui"
          ports:
            - containerPort: 8300
              name: server-rpc
            - containerPort: 8301
              name: serf-lan
            - containerPort: 8302
              name: serf-wan
            - containerPort: 8500
              name: http-api
            - containerPort: 8600
              name: dns-api
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
            - name: consul-config
              mountPath: /etc/consul/config
            - name: consul-secrets
              mountPath: /etc/consul/secrets
            - name: consul-data
              mountPath: /consul/data
          readinessProbe:
            httpGet:
              path: /v1/operator/raft/configuration
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 30
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - consul leave
      volumes:
        - name: tls
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: consul-secrets
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: consul-config
          configMap:
            name: consul
        - name: consul-scripts
          configMap:
            name: consul-scripts
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
