apiVersion: v1
kind: ConfigMap
metadata:
  name: goldfish
  namespace: vault
data:
  config.hcl: |
      listener "tcp" {
          address = "0.0.0.0:8000"
          tls_disable = 0
          tls_cert_file = "/etc/tls/cert.pem"
          tls_key_file = "/etc/tls/key.pem"
      }
      vault {
          address         = "https://vault-server.vault.svc.cluster.local"
          ca_cert         = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          tls_skip_verify = 0

          runtime_config  = "goldfish-secret/runtime-config"
      
          approle_login   = "null"
          approle_id      = "null"
      }
      disable_mlock = 1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: vault
  name: goldfish
  labels:
    app: goldfish
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goldfish
    spec:
      serviceAccountName: goldfish
      initContainers:
        - name: certificate-requestor
          image: gcr.io/the-psf/certificate-requestor:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "--additional-dnsnames=goldfish,goldfish.$(NAMESPACE),goldfish.$(NAMESPACE).svc.cluster.local"
            - "--cert-dir=/etc/tls"
            - "--namespace=$(NAMESPACE)"
            - "--pod-ip=$(POD_IP)"
            - "--pod-name=$(POD_NAME)"
            - "--service-names=goldfish"
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
        - name: vault-token-requestor
          image: gcr.io/the-psf/secure-sidecar:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "kube_login"
            - "--namespace=$(NAMESPACE)"
            - "--vault-kubernetes-auth-role=goldfish"
            - "--vault-kubernetes-auth-addr=https://vault-server.vault.svc.cluster.local"
            - "--vault-kubernetes-auth-token-path=/var/run/secrets/vault"
            - "--wrap"
          volumeMounts:
            - name: vault-token
              mountPath: /var/run/secrets/vault
      containers:
        - name: goldfish
          image: gcr.io/the-psf/goldfish:v1.0.0a1
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ['goldfish']
          args:
            - "-config=/etc/goldfish/config.hcl"
            - "-wrapped-token-file=/var/run/secrets/vault/wrapped-vault-token"
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
            - name: goldfish-config
              mountPath: /etc/goldfish
            - name: vault-token
              mountPath: /var/run/secrets/vault
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add:
              - IPC_LOCK
      volumes:
        - name: tls
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: vault-token
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: goldfish-config
          configMap:
            name: goldfish
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goldfish
  name: goldfish
  namespace: vault
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: goldfish
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
